### PR TITLE
Add MIT license

### LINKED ISSUE #4: License?
Is this MIT licensed? If so i can provide a pull request to add the license.

And also, is it possible to get this repository tagged with versions?

### PR DESCRIPTION
**Pull request by chrisl8888**
Fixes #4

### CODE REVIEW

**Comment by hollowdoor** [comment]
Thank you. :) I'll have it updated on npm hopefully by tomorrow. As it's only a plain text file change -- it will be fine till then.

**Comment by chrisl8888** [comment]
np. thank you! now i can use this :+1: 

Thanks for your work.

**Comment by hollowdoor** [comment]
You're welcome. Your contribution has been taken as advice. From now on I will be adding the license to libraries I put on github just to make sure.

**Comment by chrisl8888** [comment]
Yeah technically the MIT license needs to be packaged with all zips so that it's never a question from our legal team. I can point them to the NPM website but; they prefer it to be there.

**Comment by hollowdoor** [comment]
Yes I can understand how it makes it easier to have it in there. Especially for complex proprietary projects that consume the library.

**Pull request merged**
