### PR TITLE
Add ability to destroy autoscroller

### PR DESCRIPTION
**Pull request by cinaglia**
Useful when building complex applications where events need to be cleaned up before leaving a page and rendering a different one.

### CODE REVIEW

**Comment by hollowdoor** [comment]
Looks fine. Seems like a natural thing being there is a destroy method on the pointer.

**Comment by hollowdoor** [comment]
autoscroller on npm is updated so this and the functionality from the previous pull request are ready to use from there.

**Comment by cinaglia** [comment]
Thanks for the merge!

**Comment by hollowdoor** [comment]
No problem. I should have added this from the start. Got sidetracked. :)

**Pull request merged**
